# Recurrent Neural Network

## Part 1 - Data Preprocessing

### Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Importing the training set

In [6]:
dataset_train = pd.read_csv('Google_Stock_Price_Train.csv')
dataset_train

Date    Open    High     Low   Close      Volume
0       1/3/2012  325.25  332.83  324.97  663.59   7,380,500
1       1/4/2012  331.27  333.87  329.08  666.45   5,749,400
2       1/5/2012  329.83  330.75  326.89  657.21   6,590,300
3       1/6/2012  328.34  328.77  323.68  648.24   5,405,900
4       1/9/2012  322.04  322.29  309.46  620.76  11,688,800
5      1/10/2012  313.70  315.72  307.30  621.43   8,824,000
6      1/11/2012  310.59  313.52  309.40  624.25   4,817,800
7      1/12/2012  314.43  315.26  312.08  627.92   3,764,400
8      1/13/2012  311.96  312.30  309.37  623.28   4,631,800
9      1/17/2012  314.81  314.81  311.67  626.86   3,832,800
10     1/18/2012  312.14  315.82  309.90  631.18   5,544,000
11     1/19/2012  319.30  319.30  314.55  637.82  12,657,800
12     1/20/2012  294.16  294.40  289.76  584.39  21,231,800
13     1/23/2012  291.91  293.23  290.49  583.92   6,851,300
14     1/24/2012  292.07  292.74  287.92  579.34   6,134,400
15     1/25/2012  287.68  288.27  282.13  567.93  10,012,700
16     1/26/2012  284.92  286.17  281.22  566.54   6,476,500
17     1/27/2012  284.32  289.08  283.60  578.39   7,262,000
18     1/30/2012  287.95  288.92  285.63  576.11   4,678,400
19     1/31/2012  290.41  290.91  286.50  578.52   4,300,700
20      2/1/2012  291.38  291.66  288.49  579.24   4,658,700
21      2/2/2012  291.34  292.11  289.95  583.51   4,847,400
22      2/3/2012  294.23  297.42  292.93   594.7   6,360,700
23      2/6/2012  296.39  304.27  295.90  607.42   7,386,700
24      2/7/2012  302.44  303.56  300.75  605.11   4,199,700
25      2/8/2012  303.18  304.53  301.24  608.18   3,686,400
26      2/9/2012  304.87  306.10  303.36  609.79   4,546,300
27     2/10/2012  302.81  302.93  300.87  604.25   4,667,700
28     2/13/2012  304.11  305.77  303.87  610.52   3,646,100
29     2/14/2012  304.63  304.86  301.25  608.09   3,620,900
...          ...     ...     ...     ...     ...         ...
1228  11/17/2016  766.92  772.70  764.23  771.23   1,304,000
1229  11/18/2016  771.37  775.00  760.00  760.54   1,547,100
1230  11/21/2016  762.61  769.70  760.60   769.2   1,330,600
1231  11/22/2016  772.63  776.96  767.00  768.27   1,593,100
1232  11/23/2016  767.73  768.28  755.25  760.99   1,478,400
1233  11/25/2016  764.26  765.00  760.52  761.68     587,400
1234  11/28/2016  760.00  779.53  759.80  768.24   2,188,200
1235  11/29/2016  771.53  778.50  768.24  770.84   1,616,600
1236  11/30/2016  770.07  772.99  754.83  758.04   2,392,900
1237   12/1/2016  757.44  759.85  737.03  747.92   3,017,900
1238   12/2/2016  744.59  754.00  743.10   750.5   1,452,500
1239   12/5/2016  757.71  763.90  752.90  762.52   1,394,200
1240   12/6/2016  764.73  768.83  757.34  759.11   1,690,700
1241   12/7/2016  761.00  771.36  755.80  771.19   1,761,000
1242   12/8/2016  772.48  778.18  767.23  776.42   1,488,100
1243   12/9/2016  780.00  789.43  779.02  789.29   1,821,900
1244  12/12/2016  785.04  791.25  784.35  789.27   2,104,100
1245  12/13/2016  793.90  804.38  793.34   796.1   2,145,200
1246  12/14/2016  797.40  804.00  794.01  797.07   1,704,200
1247  12/15/2016  797.34  803.00  792.92  797.85   1,626,500
1248  12/16/2016  800.40  800.86  790.29   790.8   2,443,800
1249  12/19/2016  790.22  797.66  786.27   794.2   1,232,100
1250  12/20/2016  796.76  798.65  793.27  796.42     951,000
1251  12/21/2016  795.84  796.68  787.10  794.56   1,211,300
1252  12/22/2016  792.36  793.32  788.58  791.26     972,200
1253  12/23/2016  790.90  792.74  787.28  789.91     623,400
1254  12/27/2016  790.68  797.86  787.66  791.55     789,100
1255  12/28/2016  793.70  794.23  783.20  785.05   1,153,800
1256  12/29/2016  783.33  785.93  778.92  782.79     744,300
1257  12/30/2016  782.75  782.78  770.41  771.82   1,770,000

[1258 rows x 6 columns]

Now We see The dataset_train.iloc[:, 1:2] which means that he wants all rows :  and he wants the column number 1 which is open 

In [12]:
dataset_train.iloc[:, 1:2]

Open
0     325.25
1     331.27
2     329.83
3     328.34
4     322.04
5     313.70
6     310.59
7     314.43
8     311.96
9     314.81
10    312.14
11    319.30
12    294.16
13    291.91
14    292.07
15    287.68
16    284.92
17    284.32
18    287.95
19    290.41
20    291.38
21    291.34
22    294.23
23    296.39
24    302.44
25    303.18
26    304.87
27    302.81
28    304.11
29    304.63
...      ...
1228  766.92
1229  771.37
1230  762.61
1231  772.63
1232  767.73
1233  764.26
1234  760.00
1235  771.53
1236  770.07
1237  757.44
1238  744.59
1239  757.71
1240  764.73
1241  761.00
1242  772.48
1243  780.00
1244  785.04
1245  793.90
1246  797.40
1247  797.34
1248  800.40
1249  790.22
1250  796.76
1251  795.84
1252  792.36
1253  790.90
1254  790.68
1255  793.70
1256  783.33
1257  782.75

[1258 rows x 1 columns]

In [14]:
# I wondered why didn't he just say [: , 1] which means I want all rows in the open column alone.
dataset_train.iloc[:, 1]

0       325.25
1       331.27
2       329.83
3       328.34
4       322.04
5       313.70
6       310.59
7       314.43
8       311.96
9       314.81
10      312.14
11      319.30
12      294.16
13      291.91
14      292.07
15      287.68
16      284.92
17      284.32
18      287.95
19      290.41
20      291.38
21      291.34
22      294.23
23      296.39
24      302.44
25      303.18
26      304.87
27      302.81
28      304.11
29      304.63
         ...  
1228    766.92
1229    771.37
1230    762.61
1231    772.63
1232    767.73
1233    764.26
1234    760.00
1235    771.53
1236    770.07
1237    757.44
1238    744.59
1239    757.71
1240    764.73
1241    761.00
1242    772.48
1243    780.00
1244    785.04
1245    793.90
1246    797.40
1247    797.34
1248    800.40
1249    790.22
1250    796.76
1251    795.84
1252    792.36
1253    790.90
1254    790.68
1255    793.70
1256    783.33
1257    782.75
Name: Open, Length: 1258, dtype: float64

doing so returned a series as opposed to a dataframe. Now we see what happens when you make that series into an array. 

In [15]:
dataset_train.iloc[:, 1].values

array([ 325.25,  331.27,  329.83, ...,  793.7 ,  783.33,  782.75])

It becomes a one dimentional array and for some reason that shape is not reccomended. As opposed to the vertical look of the array as you see down here. 

In [11]:
training_set = dataset_train.iloc[:, 1:2].values
training_set

array([[ 325.25],
       [ 331.27],
       [ 329.83],
       ..., 
       [ 793.7 ],
       [ 783.33],
       [ 782.75]])

## Feature Scaling

In [16]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0, 1))
training_set_scaled = sc.fit_transform(training_set)


In [17]:
training_set_scaled

array([[ 0.08581368],
       [ 0.09701243],
       [ 0.09433366],
       ..., 
       [ 0.95725128],
       [ 0.93796041],
       [ 0.93688146]])

# Creating a data structure with 60 timesteps and 1 output

In [18]:

X_train = []
y_train = []
for i in range(60, 1258):
    X_train.append(training_set_scaled[i-60:i, 0])
    y_train.append(training_set_scaled[i, 0])
X_train, y_train = np.array(X_train), np.array(y_train)


So predictor is 60 rows before the responce, which means that the first 60 has no responce. So it is a shifting/transplacment thing. 

In [20]:
X_train = []
y_train = []

My first thought into this was sliding windows. so this is a for loop that loops over in iterations of ones starting from 60 and ending in 1258 which is len (training_set_scaled). 


training_set_scaled[i-60:i, 0] 
This means that starting by 60 

training_set_scaled[60-60:60, 0] 

training_set_scaled[60, 0]      


So the list y_train which has the responce variable starting by the 2nd month of the time series and the for loop will keep looping until the very last element in the list. So it will just take in from the second month , everyday to the last day in the series and this should be a small list. 


Therefore for every single record in the dataset put into y_train , we have a full array with the same index to predict it. 

In [21]:
for i in range(60, 1258):
    X_train.append(training_set_scaled[i-60:i, 0])
    y_train.append(training_set_scaled[i, 0])

In [22]:
X_train

[array([ 0.08581368,  0.09701243,  0.09433366,  0.09156187,  0.07984225,
         0.0643277 ,  0.0585423 ,  0.06568569,  0.06109085,  0.06639259,
         0.0614257 ,  0.07474514,  0.02797827,  0.02379269,  0.02409033,
         0.0159238 ,  0.01078949,  0.00967334,  0.01642607,  0.02100231,
         0.02280676,  0.02273235,  0.02810849,  0.03212665,  0.0433812 ,
         0.04475779,  0.04790163,  0.0440695 ,  0.04648783,  0.04745517,
         0.04873875,  0.03936305,  0.04137213,  0.04034898,  0.04784582,
         0.04325099,  0.04356723,  0.04286033,  0.04602277,  0.05398467,
         0.05738894,  0.05714711,  0.05569611,  0.04421832,  0.04514845,
         0.04605997,  0.04412531,  0.03675869,  0.04486941,  0.05065481,
         0.05214302,  0.05612397,  0.05818885,  0.06540665,  0.06882953,
         0.07243843,  0.07993526,  0.07846566,  0.08034452,  0.08497656]),
 array([ 0.09701243,  0.09433366,  0.09156187,  0.07984225,  0.0643277 ,
         0.0585423 ,  0.06568569,  0.06109085,  0

In [23]:
y_train

[0.086278740977751345,
 0.084716124711660123,
 0.074540516407470836,
 0.078837711139221667,
 0.072382617754297107,
 0.066634422204033039,
 0.063155740754520462,
 0.067824986978197721,
 0.068234243619316959,
 0.076010119800580478,
 0.080828186621028308,
 0.058077237889723854,
 0.044683384180370544,
 0.044218319815462426,
 0.042023216013096221,
 0.04070243321675715,
 0.030173375995237728,
 0.035121660837859947,
 0.040460599747004999,
 0.046859885408140456,
 0.050673413200386985,
 0.048794553166158217,
 0.04027457400104173,
 0.037874841878115961,
 0.045669320633975774,
 0.042246446908252078,
 0.032126646327851782,
 0.041874395416325649,
 0.043083562765086625,
 0.048775950591561812,
 0.04635761589403975,
 0.037484187811593128,
 0.041706972244958784,
 0.053407991666046595,
 0.068104025597142681,
 0.060011905647741615,
 0.037223751767244573,
 0.049203809807277343,
 0.038284098519235088,
 0.045241461418260243,
 0.037688816132152692,
 0.03287074931170475,
 0.025783168390505318,
 0.026304040479